### ISSUE TITLE
Standalone lines should be removed from the template

### ISSUE THREAD

**Issue by mihe** [kainjow/Mustache#12]
As far as I can tell, this implementation doesn't follow [the Mustache spec](https://github.com/mustache/spec/blob/83b0721610a4e11832e83df19c73ace3289972b9/specs/sections.yml#L211-L237) when it comes to trimming lines that only contain tags (and whitespace).

Any reason why you're not testing against the official spec tests?

**Comment by kainjow** [comment]
Indeed that part looks to have been overlooked. I'll look into it.

I can look into testing against the official spec. I don't remember why it wasn't included, probably related to having to use a third-party json library :)

**Comment by mihe** [comment]
> probably related to having to use a third-party json library

Fair point.

If you really want to avoid dealing with JSON at runtime (in the tests) you could potentially generate Catch tests from the JSON/YAML as a one-off thing. You'd of course have to redo it if you ever wanted to target a newer version of the spec, but that's the trade-off I guess. Otherwise there are some decent single-header JSON libraries out there, like [nlohmann/json](https://github.com/nlohmann/json), that could be bundled with the repo.

**Comment by kainjow** [comment]
I've used nlohmann son before, but it requires higher GCC version than what the current CI tests are running. There is picojson which I'd probably use instead. I'd probably set it up as an external project in CMake so users who don't run the tests don't need to download the extra files.

**Comment by KingDuckZ** [comment]
I'd like to use this library in one of my FOSS projects, but I'm having the same problem. Is there a fix coming anytime soon?

**Comment by kainjow** [comment]
I'll start looking into it.

**Comment by kainjow** [comment]
I think in order to implement this I need to rewrite the parser and tokenize the text. Then I'd also have to refactor rendering to keep the line state before and after tags and only render the line if the rendered tag is not empty. Not trivial work... I'll keep thinking about it. No guarantee on a timeline though :)

**Comment by kainjow** [comment]
I started a branch `standalone-lines` to work on this, starting off with the refactoring.

**Comment by kainjow** [comment]
The new parser is now done: https://github.com/kainjow/Mustache/blob/65427c7738d74864f2cc3e69896bbf60654a5f59/tests.cpp#L1204

Last step is refactoring the renderer.

**Comment by traversaro** [comment]
Hi @kainjow , thanks for the great work on the library. 

I wanted to check the experimental `standalone-lines` branch. 
I do not know if this is because the branch is a work in progress, but while compiling the branch `standalone-lines` in Ubuntu 16.04 I get the following compilation errors:  
~~~
Scanning dependencies of target mustache
[ 50%] Building CXX object CMakeFiles/mustache.dir/tests.cpp.o
In file included from /home/straversaro/src/Mustache/tests.cpp:29:0:
/home/straversaro/src/Mustache/mustache.hpp:498:32: error: declaration of ‘kainjow::mustache::delimiter_set<string_type> kainjow::mustache::context_internal<string_type>::delimiter_set’ [-fpermissive]
     delimiter_set<string_type> delimiter_set;
                                ^
/home/straversaro/src/Mustache/mustache.hpp:399:7: error: changes meaning of ‘delimiter_set’ from ‘class kainjow::mustache::delimiter_set<string_type>’ [-fpermissive]
 class delimiter_set {
       ^
/home/straversaro/src/Mustache/mustache.hpp:524:49: error: declaration of ‘std::shared_ptr<kainjow::mustache::delimiter_set<string_type> > kainjow::mustache::tag<string_type>::delimiter_set’ [-fpermissive]
     std::shared_ptr<delimiter_set<string_type>> delimiter_set;
                                                 ^
/home/straversaro/src/Mustache/mustache.hpp:399:7: error: changes meaning of ‘delimiter_set’ from ‘class kainjow::mustache::delimiter_set<string_type>’ [-fpermissive]
 class delimiter_set {
       ^
/home/straversaro/src/Mustache/mustache.hpp:557:22: error: declaration of ‘kainjow::mustache::tag<string_type> kainjow::mustache::component<string_type>::tag’ [-fpermissive]
     tag<string_type> tag;
                      ^
/home/straversaro/src/Mustache/mustache.hpp:519:7: error: changes meaning of ‘tag’ from ‘class kainjow::mustache::tag<string_type>’ [-fpermissive]
 class tag {
       ^
CMakeFiles/mustache.dir/build.make:62: recipe for target 'CMakeFiles/mustache.dir/tests.cpp.o' failed
make[2]: *** [CMakeFiles/mustache.dir/tests.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mustache.dir/all' failed
make[1]: *** [CMakeFiles/mustache.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
~~~

**Comment by kainjow** [comment]
@traversaro yes it's still a work in progress.

**Comment by KingDuckZ** [comment]
Hi @kainjow, did you get to do any progress on this? I'm sorry I can't help with any code contributions myself :(

**Comment by kainjow** [comment]
I merged the changes so far into master, but still only the refactoring part. Hadn't continued on this yet.

**Comment by traversaro** [comment]
Thanks @kainjow !

**Comment by kainjow** [comment]
I now have the 5 standalone lines tests that are in the spec link above passing! You can find the code https://github.com/kainjow/Mustache/tree/remove-standalone-lines if you'd like to test. However 2 lambda tests are failing, so that may break if you're using those.

**Comment by kainjow** [comment]
I posted a 4.0 beta if you'd like to try it before it's released:

https://github.com/kainjow/Mustache/releases

**Comment by KitsuneRal** [comment]
Thanks! I can make my templates much much more readable now. One thing that still doesn't work:
```
Text1
{{#section}}
Text2
{{/section}}
Text3
```
In case when section is a list of several (say, 3) items, the output is as follows:
```
Text1
Text2

Text2

Text2
Text3
```
which does not quite correspond to the statement "Standalone lines should be removed from the template".

**Comment by kainjow** [comment]
Ah good find, I’ll fix.

**Comment by kainjow** [comment]
@KitsuneRal  Fixed in d7fa601094f53485ff8be9a39e49928355b9f289, posted beta 2: https://github.com/kainjow/Mustache/releases

**Comment by KitsuneRal** [comment]
Thanks, that was quick! Here's a bit more (if you prefer, I can put those to separate issues, or keep them coming here). I managed to crash (rather than issue an error) Mustache on assertion in line 632, with `control == walk_control::stop`, using the following template:
```
{{#section1}}
    {{#section2}}
        {{^section3?}}{{/section4}} {{!Mind unmatching section names}}
{{/section2}}{{/section1}}
```
This snippet, in turn, came during investigation of partials eating spaces to the left of them. Specifically, if `passPartial` is defined as `{{#existingSection}}{{/existingSection}}` and `partial` is `{{#existingSection}}Text{{/existingSection}}` then
```
    {{#nonExistentSection}}{{/nonExistentSection}} {{!keeps spaces to the left}}
    {{#existingSection}}{{/existingSection}} {{!ditto}}
    {{>passPartial}} {{!eats spaces to the left of it}}
    {{>partial}} {{!behaves as a non-partial case, preserving spaces and substituting Text}}
```

**Comment by kainjow** [comment]
Separate issues would be easier to track, thanks!

**Comment by KitsuneRal** [comment]
Will move on to make them then.

**Comment by kainjow** [comment]
Version 4.0 has just been released with this feature.
